### ISSUE TITLE
Hydration error with NextJS 15

### ISSUE THREAD

**Issue by clementpicot** [Featurable/react-google-reviews#3]
Hey there!

First of all, thanks for this tool. It looks amazing!

As said in the title, I get an hydration error when using the component with NextJS 15.0.3

<img width="991" alt="image" src="https://github.com/user-attachments/assets/47bb9fd9-a2ba-42ab-a23d-baffa956b413">

If you need anything that can help you debugging, I'd love to help!

Have a good day

**Comment by ryanschiang** [comment]
Thanks for reporting this issue! I've tried to replicate it in NextJS 15.03 unfortunately to no avail. 

Can you provide some details so I can replicate?
- Browser you're using
- Full hydration error message in the console
- Component code
- Rendering strategy you're using (pages router/app router, SSR/SSG/ISR)

I have also read some users reporting hydration errors like this on NextJS 15 [caused by Chrome extensions](https://www.reddit.com/r/nextjs/comments/1gabiqn/hydration_error_when_installing_nextjs_15/), so if you could please try opening the page in Incognito or with extensions disabled.

Thanks!

**Comment by clementpicot** [comment]
Here a the details you asked for :

- **BROWSER :**
Arc (Version 1.66.0), Chromium Engine Version 130.0.6723.70

- **HYDRATION ERROR :**
<img width="1114" alt="image" src="https://github.com/user-attachments/assets/e59f89b7-14b1-4cb1-b82f-a80ce0690a69">

- **COMPONENT CODE :**
<img width="636" alt="image" src="https://github.com/user-attachments/assets/a73965d2-e086-4591-9870-d95a8414efd7">

- **RENDERING STRATEGY :**
I use App router + SSR !

**Comment by ryanschiang** [comment]
Thank you. I'm working on debugging, but cannot reproduce the hydration error. It seems to related to EmotionCSS styling.

To help track this down further, could you:
- Try creating a minimal reproduction in a fresh NextJS 15 project using `react-google-reviews@1.3.1`
- Share your `package.json` and `next.config.js`  to see any additional dependencies or config that might be affecting the rendering

Thanks!

**Comment by JosephSimmons** [comment]
Hi both, thanks for raising this @clementpicot. Did this ever get resolved? I'm having the same issue. Thanks
